name: build

on:
  push:
    branches:
      - feature/**
      - feat/**
      - hotfix/**
      - fix/**
      - dependabot/**
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Maven build & test
        run: >-
          mvn -Pcoverage
          verify
          --batch-mode --no-transfer-progress -Dsilent=true

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: always()
